author = Artur Tarassow
email = atecon@posteo.de
version = 0.95
date = 2023-12-06
description = Scatterplot matrix with factor separation
tags = C88
min-version = 2020e
gui-main = GUI_PairPlot
label = Pair Plot
menu-attachment = MAINWIN/View/GraphVars
public = PairPlot GUI_PairPlot
no-print = GUI_PairPlot
help = PairPlot_help.md
sample-script = PairPlot_sample.inp
data-files = iris.gdt
